version: '3'
services:
  opensearch-node:
    image: opensearchproject/opensearch:2.3.0
    container_name: opensearch-node
    environment:
      - DISABLE_SECURITY_PLUGIN=true
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - opensearch-net
  
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.3.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch-node:9200"]'
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    networks:
      - opensearch-net
  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  
  #jobmanager:
  #  image: flink:metis
  #  build:
  #    context: .
  #    dockerfile: flink/Dockerfile
  #  ports:
  #    - "8081:8081"
  #  command: jobmanager
  #  environment:
  #    - |
  #      FLINK_PROPERTIES=
  #      jobmanager.rpc.address: jobmanager        

  #taskmanager:
  #  image: flink:metis
  #  build:
  #    context: .
  #    dockerfile: flink/Dockerfile
  #  depends_on:
  #    - jobmanager
  #  command: taskmanager
  #  scale: 1
  #  environment:
  #    - |
  #      FLINK_PROPERTIES=
  #      jobmanager.rpc.address: jobmanager
  #      taskmanager.numberOfTaskSlots: 4

  #sql-client:
  #  image: flink:metis
  #  build:
  #    context: .
  #    dockerfile: flink/Dockerfile
  #  command: bin/sql-client.sh
  #  depends_on:
  #    - jobmanager
  #  environment:
  #    - |
  #      FLINK_PROPERTIES=
  #      jobmanager.rpc.address: jobmanager
  #      rest.address: jobmanager 

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  opensearch-data:

networks:
  opensearch-net:
